name: Trigger auto deployment for yozu-image-recommend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/yozu-image-recommend-AutoDeployTrigger-27781896-f494-4f1b-a7bd-efb3c6fc8e78.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.YOZUIMAGERECOMMEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.YOZUIMAGERECOMMEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.YOZUIMAGERECOMMEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.YOZUIMAGERECOMMEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.YOZUIMAGERECOMMEND_REGISTRY_PASSWORD }}
          containerAppName: yozu-image-recommend
          resourceGroup: DefaultResourceGroup-CID
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


